# Generated by Django 4.2.4 on 2023-08-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
