# Generated by Django 4.2.4 on 2023-09-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
