# Generated by Django 4.2.4 on 2023-09-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_profile',
            field=models.ImageField(blank=True, null=True, upload_to='default/'),
        ),
    ]
