# Generated by Django 4.2.4 on 2023-09-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_default_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_profile', models.ImageField(blank=True, null=True, upload_to='default/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_profile',
        ),
    ]
